<a href="https://colab.research.google.com/github/LJM-405/colab_project/blob/main/ch08_3_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

def conv2d(image, kernel):
  image_h, image_w = image.shape

  padded_image = np.pad(
      image,
      ((1, 1), (1, 1)),
      mode='constant'
  )
  output = np.zeros((image_h, image_w))

  for i in range(image_h):
    for j in range(image_w):
      region = padded_image[i:i+3, j:j+3]
      output[i, j] = np.sum(region * kernel)

  return output

In [ ]:
def conv2d(image, kernel):

    image_h, image_w = image.shape

    # Zero Padding
    zero_padded_image = np.pad(
        image,
        ((1, 1), (1, 1)),
        mode='constant',
        constant_values=0
    )


    output = np.zeros((image_h, image_w))

    for i in range(image_h):
        for j in range(image_w):
            region = zero_padded_image[i:i+3, j:j+3]
            output[i, j] = np.sum(region * kernel)

    return output

In [ ]:
test_image = np.array([
    [10, 10, 10, 0, 0],
    [10, 10, 10, 0, 0],
    [10, 10, 10, 0, 0],
    [0, 0, 0, 0, 0,],
    [0, 0, 0, 0, 0,]
    ])

test_kernel = np.array([
    [0, 1, 0],
    [1, -4, 1],
    [0, 1, 0]
    ])

result_feature_map = conv2d(test_image, test_kernel)

print("=== 원본 입력 이미지 (5x5) ===")
print(test_image)

print("\n=== 적용된 커널 (3x3) ===")
print(test_kernel)

print("\n=== 합성곱 연산 결과 특징 맵 (5x5) ===")
print(result_feature_map)


=== 원본 입력 이미지 (5x5) ===
[[10 10 10  0  0]
 [10 10 10  0  0]
 [10 10 10  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]

=== 적용된 커널 (3x3) ===
[[ 0  1  0]
 [ 1 -4  1]
 [ 0  1  0]]

=== 합성곱 연산 결과 특징 맵 (5x5) ===
[[-20. -10. -20.  10.   0.]
 [-10.   0. -10.  10.   0.]
 [-20. -10. -20.  10.   0.]
 [ 10.  10.  10.   0.   0.]
 [  0.   0.   0.   0.   0.]]
